development:
  adapter: redis
  url: redis://redis-test.ijpwsg.ng.0001.euw2.cache.amazonaws.com:6379

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis-test.ijpwsg.ng.0001.euw2.cache.amazonaws.com:6379
